Added automatic tool to generate the definition file
newrelic/nr-integration-definitions pull request #8
Opened 2020-09-08 09:48 UTC by paologallinaharbur

### Use Case

This change is driven by https://github.com/newrelic/nr-integration-definitions/issues/5, basically we need to provide an easy way to generate integration file and a step to step guide to accomplish that.

I've chosen to provide the tool as a Docker container in order to avoid any python requirement since different tools can be provided with different languages.

### The tool
The tool is basically the one we already had, I added the possibility to scrape directly an URL, refactored a bit the code.
Now it supports as well exporter output having more that one service, it will append more than one definition in the same file using `---` as delimiter

This closes #5

2020-09-09 14:30 UTC, theletterf submitted a review, later dismissed

2020-09-09 16:49 UTC, ardias requested changes

2020-09-14 13:59 UTC, gsanchezgavier requested changes
_total metrics are being modified

2020-09-16 12:20 UTC, ardias submitted a review, later dismissed

2020-09-18 13:06 UTC, ardias approved these changes

2020-09-22 14:18 UTC, gsanchezgavier approved these changes

2020-09-22 14:19 UTC, merged